/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DND;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  @DisplayName("Pdf Parsing")
  void pdf() {
    PdfParse pdf = new PdfParse(
        "C:/Users/thoma/Documents/Java Projects/DND/app/src/main/java/DND/D&D 5e - Players Handbook.pdf");
    assertNotEquals("", pdf.reuturnObject());
  }

  @Test
  @DisplayName("Basic roll test")
  public void basicRoll() {
    try {
      Roll rollDice = new Roll(1);
      int roll = rollDice.roll("1d6");
      System.out.println(roll);
      assertEquals(4, roll);
    } catch (FormatException e) {
      e.printStackTrace();
    }
  }

  @Test
  @DisplayName("Multi-Die test")
  public void complexRoll() {
    Roll dice = new Roll(1);
    try {
      int roll = dice.roll("5d8");
      assertEquals(17, roll)
    } catch (FormatException e) {
      e.printStackTrace();
    }
  }
}
