/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DND;

public class App {
    public static void main(String[] args) {
        PdfParse pdf = new PdfParse("C:/Users/thoma/Documents/School/Players Handbook.pdf");
        pdf.reuturnObject();
    }
}
